[project]
name = "refcloud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jeremy Adams", email = "jeremy.adams@ga4gh.org" }
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.36",
    "click>=8.4.2",
    "psycopg[binary]>=3.3.4",
    "sqlalchemy>=2.0.51",
]

[project.scripts]
refcloud = "refcloud:main"

[build-system]
requires = ["uv_build>=0.11.24,<0.12.0"]
build-backend = "uv_build"
